name: sync-to-bitbucket

# on: 
#   push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # <-- clone with complete history

      - uses: yesolutions/mirror-action@v0.7.0
        with:
            REMOTE: ssh://git@bitbucket.org/dirkarnez/${{ github.event.repository.name }}.git
            GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
            GIT_SSH_NO_VERIFY_HOST: "true"
